version: 2

workflows:
  version: 2
  default:
    jobs:
    - test
    - build
    - docker:
        requires:
          - test
          - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.13.5
    steps:
      - checkout
      - run:
          name: build binary
          command: make build/linux/pentagon
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    docker:
      - image: circleci/golang:1.13.5
    steps:
      - checkout
      - run:
          name: unit tests
          command: make test
      - run:
          name: vet
          command: go vet ./...

  docker:
    docker:
      - image: circleci/golang:1.13.5
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: login
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      - run:
          name: docker image
          command: make docker
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make docker-push
            fi